# before_script:
# - git lfs checkout

language: node_js
node_js:
  - '9'

branches:
  only:
    - master

stages:
  - release

jobs:
  include:
    - stage: release
      if: type != pull_request
      script: npx -p @semantic-release/changelog@3.0.4 -p @semantic-release/github@5.4.3 -p semantic-release@15.13.24 semantic-release